[package]
name = "variables_and_mutability"
version = "0.1.0"
authors = ["swarajd <swaraj.dhumne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
